# Generated by Django 4.0.6 on 2022-07-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('text', models.TextField(max_length=500, verbose_name='내용')),
                ('like', models.BooleanField(default=False, verbose_name='좋아요')),
            ],
        ),
    ]
