# Generated by Django 4.0.6 on 2022-07-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_ideastar_idea_created_at_idea_like_idea_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(max_length=100, verbose_name='관심도'),
        ),
    ]
