# Generated by Django 4.0.6 on 2022-07-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('year', models.CharField(max_length=4, verbose_name='개봉년도')),
                ('genre', models.CharField(max_length=50, verbose_name='장르')),
                ('grade', models.IntegerField(verbose_name='별점')),
                ('time', models.IntegerField(verbose_name='러닝타임')),
                ('review', models.TextField(verbose_name='리뷰')),
                ('director', models.CharField(max_length=50, verbose_name='감독')),
                ('actor', models.CharField(max_length=50, verbose_name='배우')),
            ],
        ),
    ]
